export const RETRIEVE_PROVIDERS_START = "RETRIEVE_PROVIDERS_START";
export const RETRIEVE_PROVIDERS_SUCCESS = "RETRIEVE_PROVIDERS_SUCCESS";
export const RETRIEVE_PROVIDERS_FAILURE = "RETRIEVE_PROVIDERS_FAILURE";

export const RETRIEVE_PROVIDERS_FORM_START = "RETRIEVE_PROVIDERS_FORM_START";
export const RETRIEVE_PROVIDERS_FORM_SUCCESS = "RETRIEVE_PROVIDERS_FORM_SUCCESS";
export const RETRIEVE_PROVIDERS_FORM_FAILURE = "RETRIEVE_PROVIDERS_FORM_FAILURE";

export const RETRIEVE_LOCATIONS_START = "RETRIEVE_LOCATIONS_START";
export const RETRIEVE_LOCATIONS_SUCCESS = "RETRIEVE_LOCATIONS_SUCCESS";
export const RETRIEVE_LOCATIONS_FAILURE = "RETRIEVE_LOCATIONS_FAILURE";

export const RETRIEVE_PRICE_START = "RETRIEVE_PRICE_START";
export const RETRIEVE_PRICE_SUCCESS = "RETRIEVE_PRICE_SUCCESS";
export const RETRIEVE_PRICE_FAILURE = "RETRIEVE_PRICE_FAILURE";

export const CREATE_ORDER_START = "CREATE_ORDER_START";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAILURE = "CREATE_ORDER_FAILURE";

export const RETRIEVE_PROVIDER_START = "RETRIEVE_PROVIDER_START";
export const RETRIEVE_PROVIDER_SUCCESS = "RETRIEVE_PROVIDER_SUCCESS";
export const RETRIEVE_PROVIDER_FAILURE = "RETRIEVE_PROVIDER_FAILURE";

export const GET_PAYMENT_STATUS_START = "GET_PAYMENT_STATUS_START";
export const GET_PAYMENT_STATUS_SUCCESS = "GET_PAYMENT_STATUS_SUCCESS";
export const GET_PAYMENT_STATUS_FAILURE = "GET_PAYMENT_STATUS_FAILURE";

export const TRACK_ORDER_START = "TRACK_ORDER_START";
export const TRACK_ORDER_SUCCESS = "TRACK_ORDER_SUCCESS";
export const TRACK_ORDER_FAILURE = "TRACK_ORDER_FAILURE";
